const data = [
    {
      id: 1,
      name: 'Mustafa Shaikh',
      company:'Credit Suisse',
      year : '13 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Mustaffa-124x150.png',
    },
    {
      id: 2,
      name: 'Nagdatt Gajjam',
      company:'Wiley Edge',
      year : '9 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Nagdatt-Hanuman-Gajjam-Cognizant-with-4.5-LPA-1-1-214x300.png',
    },
    {
      id: 3,
      name: 'Sanika Shirke',
      company:'PTC ',
      year : '8 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Sanika-Parag-Shirke-CSE-PTC-8.0-LPA-1-222x300.png',
    },
    {
      id: 4,
      name: 'Atharva Shirke',
      company:'Persistent',
      year : '7 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Atharva-Prashant-Shirke-EY-GDS-with-4.83-LPA-1-1-229x300.png',
    },
    {
      id: 5,
      name: 'Samarth Kalshetti',
      company:'Persistent',
      year : '5 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Samarth-Ashok-Kalshetti-Hitachi-with-5.0-LPA-1-1-215x300.png',
    },
    {
      id: 6,
      name: 'Iranna Patil',
      company:'Hitachi',
      year : '5 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Iranna-Baburao-Patil-Hitachi-with-5.0-LPA--217x300.png',
    },
    {
      id: 7,
      name: 'Krushnat Kapse',
      company:'TCS',
      year : '7 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Krushnat-Narayan-Kapse-TCS-with-7.0-LPA--217x300.png',
    },
    {
      id: 8,
      name: 'Rohan Pengonda',
      company:'Hexaware',
      year : '4 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Rohan-Venkatesh-Pengonda-Hexaware-with-4.0-LPA--217x300.png',
    },
    {
      id: 9,
      name: 'Diya Kudchi',
      company:'Cognizant',
      year : '4 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Diya-Javeed-Kudchi-Cognizant-with-4.0-LPA-1-1.png',
    },
    {
      id: 10,
      name: 'Harshvardhan Balla',
      company:'Tech Mahindra',
      year : '4 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Harshvadhan-Suhas-Balla-Tech-Mahindra-with-4-LPA-.png',
    },
    {
      id: 11,
      name: 'Shruti Ingale',
      company:'TCS',
      year : '7 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Shruti-Prashant-Ingale-EY-GDS-with-4.83-LPA-1-1.png',
    },
    {
      id: 12,
      name: 'Rahil Shaikh',
      company:'UNO Minda',
      year : '5 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Rahil-Hanif-Shaikh-UNO-Minda-with-4.81-LPA-.png',
    },
    {
      id: 13,
      name: 'Shrinivas Sidral',
      company:'Persistent',
      year : '5 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Shrinivas-Yallappa-Sidral-Persistent-with-5.0-LPA-.png',
    },
    {
      id: 14,
      name: 'Snehal Kortekar',
      company:'Cognizant',
      year : '4 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Snehal-Monoj-Kortekar-Cognizant-with-4.0-LPA-1-1.png',
    },
    {
      id: 15,
      name: 'Rushikesh Magar',
      company:'Hitachi',
      year : '5 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Rushikesh-Anand-Magar-Hitachi-with-5.0-LPA-.png',
    },
    {
      id: 16,
      name: 'Rutuja Gadi',
      company:'Cognizant',
      year : '4.5 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Rutuja-Mahesh-Gadi-Cognizant-with-4.5-LPA-1-1.png',
    },
    {
      id: 17,
      name: 'Alqamar Lokhandwala',
      company:'VOIS (5 LPA)',
      year : '5 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Alaqmaar-Shabbir-LokhandwalaTech-Mahindra-796x1024.jpeg',
    },
    {
      id: 18,
      name: 'Vijayalaxmi Injamuri',
      company:'Hitachi (5 LPA)',
      year : '5 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Vijayalaxmi-Prabhakar-Ingamuri-Hitachi-with-5.0-LPA-1-1.png',
    },
    {
      id: 19,
      name: 'Mahesh Vinnu',
      company:'UNO Minda',
      year : '5 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Mahesh-Anand-Vinnu-UNO-Minda-with-4.81-LPA-.png',
    },
    {
      id: 20,
      name: 'Sanket Umergi',
      company:'Hexaware',
      year : '4 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Sanket-Siddharam-Umergi-Hexaware-with-4.0-LPA-.png',
    },
    {
      id: 21,
      name: 'Tanjila Bijali',
      company:'Tech Mahindra',
      year : '4 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Tanjila-Bashirahmad-Bijali-Tech-Mahindra-with-4-LPA-.png',
    },
    {
      id: 22,
      name: 'Monesh Sutar',
      company:'VOIS',
      year : '5 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Monesh-Kashinath-Sutar-Tech-Mahindra-with-4-LPA-.png',
    },
    {
      id: 23,
      name: 'Pratik Agawane',
      company:'VOIS',
      year : '5 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Pratik-Shyamkumar-Agawane-VOIS-with-5-LPA-.png',
    },
    {
      id: 24,
      name: 'Akash Patil',
      company:'HFCC',
      year : '5.25 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Akash-Shrinivas-Patil-HFFC-.png',
    },
    {
      id: 25,
      name: 'Tanaya Deshpande',
      company:'HFCC',
      year : '4.5 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Tanaya-Umesh-Deshpande-HFFC-.png',
    },
    {
      id: 26,
      name: 'Atish Waghmare',
      company:'Trianz',
      year : '4.5 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Atish-Hanmantu-Waghmare-Trianz-with-4.5-LPA-1-1.png',
    },
    {
      id: 27,
      name: 'Farzeen Shaikh',
      company:'ATOS',
      year : '3.5 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Farzeen-Abulqasam-Shaikh-Atos-Syntel-with-3.5-LPA-.png',
    },
    {
      id: 28,
      name: 'Pavan Nili',
      company:'TCS Ninja',
      year : '3.5 LPA',
      uri: 'http://sinhgadsolapur.org/EdSite/wp-content/uploads/2017/05/Pavan-Shrinivas-Nili-TCS-with-3.36-LPA-.png',
    },

    
  ];

  export default data;