export default {
  SPLASH: 'SplashScreen',
  HOME: 'Homes',
  HOME_TAB: 'Home Tab',
  ABOUT_TAB: 'About Tab',
  EVENTS_TAB:'Events Tab',
  PLACEMENT_TAB:'Placement Tab',
  HOME_DRAWER: 'Home Drawer',
  WEBSITE: 'Web',
  ABOUT: 'About',
  EVENTS:'Events',
  PLACEMENT:'Placement',
  CSE:'Computer Science & Engineering',
  ENTC:'Electronics & Telecommunication',
  MECH:'Mechanical Engineering',
  ELECT:'Electrical Engineering',
  CIVIL:'Civil Engineering',
  GSE:'General Science Engineering',
  CAMPUS:'Campus Facilities ',
  CSEDEPT:'CSE Department',
  GSEDEPT:'GSE Department',
  CIVILDEPT:'Civil Department',
  MECHDEPT:'Mechanical Department',
  ENTCDEPT:'ENTC Department',
  ELECTDEPT:'Electrical Department',
  EVENTGALLERY:'College Events',
  GALLERY:'Gallery',
};
  
